version: 2.1
jobs:    
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: 'npm install --save'      
      - run:
          name: npm test 
          command: |
              ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-result,reportFilename=test-result
      - store_test_results:
          path: test-results          
      - store_artifacts:
          path: test-result
      